### ISSUE TITLE
After whitelisting the origin too, still it can able to access from other origin

### ISSUE THREAD

**Issue by mohamed-sedarglobal** [agungsugiarto/codeigniter4-cors#2]
Hi there,
I have added this stuff, but i m still able to use other origin 
example :

  public $allowedOrigins = ['domain.com'];
  
  i have added this stuff
  but from my local ip i can able to access the domain request.
  could you plz help me solve this.
  thanks.

**Comment by agungsugiarto** [comment]
Hello @mohamed-sedarglobal can you please share how scenario are u using with example?

**Comment by agungsugiarto** [comment]
I am test it, when whitlist with domain got error cors
![image](https://user-images.githubusercontent.com/10989147/106772810-f35a0500-6672-11eb-99d1-bbfde34c65ed.png)

**Comment by mohamed-sedarglobal** [comment]
Its working Bro !!!
Thanks.!!!
