### ISSUE TITLE
POST Request failed

### ISSUE THREAD

**Issue by goeko** [agungsugiarto/codeigniter4-cors#3]
If I send a POST request to Codeigniter4 with all CORS settings, request is failed.
If I send a GET request to Codeigniter4 with all CORS settings, request is not failed.

Is this implementation only for GET requests or what can I configure to use POST requests?

**Comment by agungsugiarto** [comment]
Try to upgrade with version 2.x-dev, make sure try with firefox or chrome to see options.

**Comment by agungsugiarto** [comment]
![image](https://user-images.githubusercontent.com/10989147/108510449-1af6d180-72f1-11eb-8691-4e17af193dfd.png)

Example request from client:
```js
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
<script type="text/javascript">
    $.ajax({
        'url': 'http://codeigniter4-appstarter.test/test',
        'headers': {
            'X-CSRF-TOKEN':'xxxxxxxxxxxxxxxxxxxx',
            'Content-Type':'application/json'
        },
        'method': 'post',
        'dataType': 'json',
        'data': {
            'firstName': 'First',
            'lastName': 'Last'
        }
    })
    .done(function(response) {
        console.log(response.callback)
    })
    .fail(function(error) {
        console.log(error)
    });
</script>
```
