### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by ypkkhatri** [agungsugiarto/codeigniter4-cors#4]
```bash
$ composer require agungsugiarto/codeigniter4-cors --ignore-platform-reqs
Using version ^2.0 for agungsugiarto/codeigniter4-cors
./composer.json has been updated
Running composer update agungsugiarto/codeigniter4-cors
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires agungsugiarto/codeigniter4-cors ^2.0 -> satisfiable by agungsugiarto/codeigniter4-cors[v2.0.0].
    - agungsugiarto/codeigniter4-cors v2.0.0 requires codeigniter4/framework ^4.1 -> satisfiable by codeigniter4/framework[v4.1.0, v4.1.1, v4.1.2, v4.1.3] from composer repo (https://repo.packagist.org) but codeigniter4/framework is the root package and cannot be modified. See https://getcomposer.org/dep-on-root for details and assistance.


Installation failed, reverting ./composer.json to its original content.
```

`Codeigniter 4.1.3`
```
CodeIgniter v4.1.3 Command Line Tool - Server Time: 2021-09-06 10:27:32 UTC-05:00

CodeIgniter development server started on http://localhost:8080
```

**Comment by CaioCoelhoChaves** [comment]
Same problem here

**Comment by AnwarQasem** [comment]
@ypkkhatri @CaioCoelhoChaves ... add "version": "4.1.4" ( where 4.1.4 is the version of codeigniter) into your composer.json.

**Comment by AngelPestana** [comment]
@ypkkhatri tengo el mismo detalle, pudiste instalarlo?

**Comment by ypkkhatri** [comment]
I will check and get back

**Comment by demyr17** [comment]
Still going on with new versions of CI

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires agungsugiarto/codeigniter4-cors ^2.0 -> satisfiable by agungsugiarto/codeigniter4-cors[v2.0.0].
    - agungsugiarto/codeigniter4-cors v2.0.0 requires codeigniter4/framework ^4.1 -> satisfiable by codeigniter4/framework[v4.1.0, ..., v4.2.10] from composer repo (https://repo.packagist.org) but codeigniter4/framework is the root package and cannot be modified. See https://getcomposer.org/dep-on-root for details and assistance.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require agungsugiarto/codeigniter4-cors:*" to figure out if any version is installable, or "composer require agungsugiarto/codeigniter4-cors:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by cijagani** [comment]
Use composer install -w

Or

composer install -W

**Comment by cijagani** [comment]
--with-dependencies (-w): Update also dependencies of packages in the argument list, except those which are root requirements.

--with-all-dependencies (-W): Update also dependencies of packages in the argument list, including those which are root requirements.

**Comment by demyr17** [comment]
> composer install -w

this is not working, saying: The "-w" option does not exist.

**Comment by AngelPestana** [comment]
@AnwarQasem me funciono la solucion que proporcionaste, agregar al archivo composer.json lo siguiente
"version": "la version del codeigniter que tienen"
y listo!!

**Comment by cijagani** [comment]
@demyr17  can you try this?

`composer require agungsugiarto/codeigniter4-cors -w`


seems you are using very old version of CI4. latest one is 4.2.10

**Comment by agungsugiarto** [comment]
already fixed with last version `v3.x`
